global using Attendence_Monitoring_System.Models;
global using Microsoft.EntityFrameworkCore;
global using Attendence_Monitoring_System.Services;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Mvc;
global using System.Security.Cryptography;
global using System.Text;
global using Microsoft.AspNetCore.Mvc.Rendering;
global using Attendence_Monitoring_System.CustomSession;